
# Package - llm.v1

# Class - Model
Model: {
  shape: class
  id: string
  name: string
  versions: repeated ModelVersion
}

Model -> ModelVersion

# Class - ModelVersion
ModelVersion: {
  shape: class
  version: string
  description: string
  metadata: repeated map<string, string>
  created_at: Timestamp
  updated_at: Timestamp
}






