
# Package - llm.v1

# Class - Output
Output: {
  shape: class
  id: string
  content: string
  rating: OutputRating
  created_at: Timestamp
}

Output -> OutputRating

# Class - OutputRating
OutputRating: {
  shape: class
  score: float
  rater: Rater
  feedback: string
  rated_at: Timestamp
}

OutputRating -> Rater





