
# Package - llm.v1

# Class - Prompt
Prompt: {
  shape: class
  id: string
  template: string
  context: repeated map<string, string>
  created_at: Timestamp
  metadata: repeated Any
}


# Class - Rater
Rater: {
  shape: class
  id: string
  type: Rater_RaterType
  qualification: string
  qualified_at: Timestamp
  metadata: repeated Any
}

  
# Enum - Rater_RaterType
Rater_RaterType: {
  grid-columns: 2
  grid-gap: 0
  Rater_RATER_TYPE_UNSPECIFIED
  Rater_RATER_TYPE_HUMAN
  Rater_RATER_TYPE_MODEL
  0
  1
  2
}

Rater -> Rater_RaterType





