
# Package - llm.v1

# Class - Prompt
Prompt: {
  shape: class
  id: string
  template: string
  context: bytes
}

# Class - Rater
Rater: {
  shape: class
  id: string
  type: string
  qualification: string
}



