
# Package - llm.v1

# Class - Prompt
Prompt: {
  shape: class
  id: string
  template: string
  context: map<string, string>
  created_at: Timestamp
  metadata: Any
}
Prompt -> Timestamp
Prompt -> Any

# Class - Rater
Rater: {
  shape: class
  id: string
  type: Rater_RaterType
  qualification: string
  qualified_at: Timestamp
  metadata: Any
}
Rater -> Rater_RaterType
Rater -> Timestamp
Rater -> Any



